# Generated by Django 3.0.3 on 2020-09-08 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='date_of_birth',
        ),
    ]
