# Generated by Django 3.0.3 on 2020-09-09 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_owner_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='first_name',
            field=models.CharField(default='', max_length=255, verbose_name='First Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='owner',
            name='last_name',
            field=models.CharField(default='', max_length=255, verbose_name='Last Name'),
            preserve_default=False,
        ),
    ]
