# Generated by Django 3.0.3 on 2020-09-07 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
